# Generated by Django 2.1 on 2018-09-23 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botchat', '0004_auto_20180922_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='family',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='order',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='phylum',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='t_class',
        ),
        migrations.AlterField(
            model_name='animal',
            name='common_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='geographic_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='botchat.Owner'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
